### ISSUE TITLE
UPLOADING IMAGES

### ISSUE THREAD

**Issue by tharindu-dm** [tharindu-dm/Kamper#7]
when uploading images using link or from device, 
Uncaught runtime errors:

```
Uncaught runtime errors:
×
ERROR
Request failed with status code 404
AxiosError: Request failed with status code 404
    at settle (http://localhost:3000/Kamper/static/js/bundle.js:53422:12)
    at XMLHttpRequest.onloadend (http://localhost:3000/Kamper/static/js/bundle.js:52085:66)
    at Axios.request (http://localhost:3000/Kamper/static/js/bundle.js:52575:41)
```

**Comment by tharindu-dm** [comment]
check these functions:

* upload by link
```
async function addPhotByLink(ev) {
    ev.preventDefault();
    const { data: filename } = await axios.post("/upload-by-link", {
      link: photoLink,
    });
    setAddedPhotos((prev) => {
      return [...prev, filename];
    });

    setPhotoLink("");
  }
```

* uploadFile
  ```
function uploadPhoto(ev) {
    const files = ev.target.files;
    const data = new FormData();

    for (let i = 0; i < files.length; i++) {
      data.append("photos", files[i]);
    }

    axios
      .post("/upload", data, {
        headers: { "Content-type": "multipart/form-data" },
      })
      .then((response) => {
        const { data: filenames } = response;
        setAddedPhotos((prev) => {
          return [...prev, ...filenames];
        });
      });
  }
```

**Comment by tharindu-dm** [comment]
upload is working but, now it doesn't show the image.
image is not rendered to the site

**Comment by tharindu-dm** [comment]
src={"http://localhost:3000/api" + link } 

generates: http://localhost:3000/uploads/uploads\62887632cb58dd17376a63767dda5329.jpg
find where the uploads\3528305y285.jpg comes from

also check whether renameing works

**Comment by tharindu-dm** [comment]
somehow the image name seems like it got an encrypted or hashed. doesn't include current date

**Comment by tharindu-dm** [comment]
IT SHOULD BE LOCALHOST:4000 !!!
