### ISSUE TITLE
when selecting features

### ISSUE THREAD

**Issue by tharindu-dm** [tharindu-dm/Kamper#9]
sometimes when selecting  and deselecting feaature checkboxes, the sent mongodb code, break values into characters and assign each character to a single element of the resulting array

**Comment by tharindu-dm** [comment]
> ERROR
> selected.filter is not a function
> TypeError: selected.filter is not a function
>     at handleCbClick (http://localhost:3000/Kamper/static/js/bundle.js:391:28)
>     at HTMLUnknownElement.callCallback (http://localhost:3000/Kamper/static/js/bundle.js:16730:18)
>     at Object.invokeGuardedCallbackDev (http://localhost:3000/Kamper/static/js/bundle.js:16774:20)
>     at invokeGuardedCallback (http://localhost:3000/Kamper/static/js/bundle.js:16831:35)
>     at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/Kamper/static/js/bundle.js:16845:29)
>     at executeDispatch (http://localhost:3000/Kamper/static/js/bundle.js:20988:7)
>     at processDispatchQueueItemsInOrder (http://localhost:3000/Kamper/static/js/bundle.js:21014:11)
>     at processDispatchQueue (http://localhost:3000/Kamper/static/js/bundle.js:21025:9)
>     at dispatchEventsForPlugins (http://localhost:3000/Kamper/static/js/bundle.js:21034:7)
>     at http://localhost:3000/Kamper/static/js/bundle.js:21194:16

**Comment by tharindu-dm** [comment]
> > ERROR
> > selected.filter is not a function
> > TypeError: selected.filter is not a function
> > at handleCbClick (http://localhost:3000/Kamper/static/js/bundle.js:391:28)
> > at HTMLUnknownElement.callCallback (http://localhost:3000/Kamper/static/js/bundle.js:16730:18)
> > at Object.invokeGuardedCallbackDev (http://localhost:3000/Kamper/static/js/bundle.js:16774:20)
> > at invokeGuardedCallback (http://localhost:3000/Kamper/static/js/bundle.js:16831:35)
> > at invokeGuardedCallbackAndCatchFirstError (http://localhost:3000/Kamper/static/js/bundle.js:16845:29)
> > at executeDispatch (http://localhost:3000/Kamper/static/js/bundle.js:20988:7)
> > at processDispatchQueueItemsInOrder (http://localhost:3000/Kamper/static/js/bundle.js:21014:11)
> > at processDispatchQueue (http://localhost:3000/Kamper/static/js/bundle.js:21025:9)
> > at dispatchEventsForPlugins (http://localhost:3000/Kamper/static/js/bundle.js:21034:7)
> > at http://localhost:3000/Kamper/static/js/bundle.js:21194:16

Fixed but the initial character array-ing thing still can happen
